version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  open-pull-requests-limit: 10
  schedule:
    interval: "weekly"
    day: "sunday"
  ignore:
    - dependency-name: "@types/node"
      update-types:
        - version-update:semver-major

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"

- package-ecosystem: "pip"
  directory: "/.github"
  schedule:
    interval: "weekly"
    day: "sunday"
  allow:
    - dependency-type: all
  commit-message:
    prefix: "chore(deps)"
  labels:
    - "dependencies"
    - "pip"
