name: Markdown

on:
  pull_request:
    paths:
      - '.github/workflows/markdown.yml'
      - '.github/markdownlint.json'
      - '.github/markdownlint.jsonc'
      - '**/*.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  linter:
    name: Lint Markdown Files
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Checkout vscode-cmsis-debugger
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Register Markdownlint Warning Matcher
        run: echo "::add-matcher::.github/markdownlint.json"

      - name: Lint Markdown Files
        uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb # v1.5.0
        with:
          args: '**/*.md'
          config: '.github/markdownlint.jsonc'

      - name: Remove Markdownlint Warning Matcher
        if: always()
        run: echo "::remove-matcher owner=markdownlint::"

  check-links:
    name: Check Markdown Links
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check Links
        uses: lycheeverse/lychee-action@82202e5e9c2f4ef1a55a3d02563e1cb6041e5332 # v2.4.1
        with:
          # Recursively scan every *.md file, show each link it checks
          args: >
            --verbose
            --no-progress
            --check
            "./**/*.md"
          jobSummary: true           # include a nice table in the run log
          fail: true                 # fail pipeline on broken links
